export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  VEHICLES: '/vehicles',
  VEHICLE_TYPES: '/vehicle-types',
  MAINTENANCE: '/maintenance',
  MAINTENANCE_NEW: '/maintenance/new',
  MAINTENANCE_EDIT: '/maintenance/:id/edit',
  ROUTES: '/routes',
  STATIONS: '/stations',
  EMPLOYEES: '/employees',
  ROLES: '/roles',
  TRIPS: '/trips',
  TRIPS_NEW: '/trips/new',
  TRIPS_EDIT: '/trips/:id/edit',
  TRIPS_STAFF: '/trips/:id/staff',
  TRIP_CALENDAR: '/trips/calendar',
  MY_SCHEDULE: '/my-schedule',
  CUSTOMERS: '/customers',
  BOOKINGS: '/bookings',
  CHECK_IN: '/check-in',
  PAYMENTS: '/payments',
} as const;
